services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lara_app
    volumes:
      - ./app:/var/www
    ports:
      - 9000:9000
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: lara_web
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mariadb:latest
    container_name: lara_db
    environment:
      MARIADB_ROOT_PASSWORD: larapasswd
      MARIADB_DATABASE: larabase
      MARIADB_USER: larauser
      MARIADB_PASSWORD: larapasswd
    ports:
      - 3306:3306
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
# volumes:
#   dbdata:

# db:
#   image: mariadb:latest
#   container_name: lara-db
#   environment:
#     MARIADB_ROOT_PASSWORD: larapasswd
#     MARIADB_DATABASE: larabase
#     MARIADB_USER: larauser
#     MARIADB_PASSWORD: larapasswd
#   ports:
#     - 3306:3306
#   volumes:
#     - ./data:/var/lib/mysql
